spring:
  profiles:
    default: development
  application:
    name: exclusion-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true


server:
  port: 9092
  servlet:
    contextPath: /exclusion/v1.0