DROP TABLE IF EXISTS EXCLUSION_USER;

CREATE TABLE EXCLUSION_USER (
  EXCLUSION_USER_ID VARCHAR(20) PRIMARY KEY NOT NULL,
  FIRST_NAME VARCHAR(35) NOT NULL,
  LAST_NAME VARCHAR(35) NOT NULL,
  DATE_OF_BIRTH VARCHAR(10) NOT NULL,
  EMAIL VARCHAR(35)  NOT NULL,
  COUNTRY VARCHAR(15) NOT NULL,
  STATUS VARCHAR(1) NOT NULL

);

INSERT INTO EXCLUSION_USER (EXCLUSION_USER_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, EMAIL, COUNTRY, STATUS) VALUES
  ('1', 'Hema', 'Tamil', '30/6/95', 'hema1@yahoo.com', 'UK', 'A'),
   ('2', 'Aravinth', 'Mouni', '30/6/95', 'hema2@yahoo.com', 'UK', 'B'),
   ('3', 'Hema', 'Alli', '30/6/95', 'hema3@yahoo.com', 'UK', 'B');

commit;